server:
  port: 8386
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
      datasource.ds2.file:
        file: "classpath: gateway.json"
        ruleType: gw-flow
      datasource.ds1.file:
        file: "classpath: api.json"
        ruleType: gw-api-group
    gateway:
      enabled: true
      discovery:
        locator:
          lower-case-service-id: true
      routes:
        # Add your routes here.
        - id: userList
          uri: http://localhost:8081
          predicates:
            - Path=/user/list
        - id: httpbin_route
          uri: http://localhost:8081
          predicates:
            - Path=/user/get/**