server.port: 8081
spring.application.name: nacos-provider
spring.cloud.nacos.discovery.server-addr: 127.0.0.1:8848
management.endpoints.web.exposure.include: '*'


mybatis:
  type-aliases-package: ken.spring.cloud.alibaba.po
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: 'classpath:/myMapper/*.xml'


spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sc_alibaba_01?useUnicode=true&characterEncoding=UTF-8
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
